### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by eaglemoor** [badkaktus/gorocket#8]
Пожалуйста, веди CHANGELOG.md с версиями, что бы люди знали что за изменения выкатились. Выехала версия v0.1.2, а не понятно что там и стоит ли на это обновляться. Спасибо.

**Comment by badkaktus** [comment]
@eaglemoor обновил changelog. Отдельный релиз для этого обновления делать не стал, в следующий раз буду сразу вписывать изменения.

ps можете подсказать, в каких кейсах используете изменения описанные в changelog.md? Изменения в рамках релиза отображаются на странице нотификаций о релизе и если просто кликнуть по релизу на главной странице репозитория.

**Comment by eaglemoor** [comment]
В принципе ни чем не отличается. Это больше правило хорошего тона. Я обычно пишу changelog, а из него копирую что мне нужно в release страницу. GitHub тут действительно далеко продвинулся. Но не все платформы так красиво это делают. И в релиз GitHub идет именно сообщение с коммита, а туда обычно не пишут много текста.

Так же есть релизы из нескольких изменений, ты можешь указать что-то типа 

```
# [v0.1.5] - Unreleased

## Added 

 - add this one
 - add this two

## Changed

 - fix this
```

И копить там изменения и потом разом зарелизить и не вспоминать что туда вносили
